name: Windows VM via Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kích hoạt Docker có sẵn
        run: |
          sudo systemctl start docker
          docker --version
          docker-compose --version || echo "docker-compose chưa có"

      - name: Cài docker-compose (nếu thiếu)
        run: |
          if ! command -v docker-compose &> /dev/null; then
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

      - name: Tạo file docker-compose
        run: |
          mkdir vm && cd vm
          cat > win11.yml <<'EOF'
          version: '3'
          services:
            windows:
              image: dockurr/windows
              container_name: windows
              environment:
                VERSION: "11"
                USERNAME: "admin"
                PASSWORD: "admin@123"
                RAM_SIZE: "8G"
                CPU_CORES: "4"
              devices:
                - /dev/kvm
                - /dev/net/tun
              cap_add:
                - NET_ADMIN
              ports:
                - "8006:8006"
                - "3389:3389/tcp"
                - "3389:3389/udp"
              stop_grace_period: 2m
              volumes:
                - /home:/storage
          EOF

      - name: Chạy Windows VM
        run: |
          cd vm
          sudo docker-compose -f win11.yml up -d
